title: My GitHub Learning
author: Due West
email: duewestatx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This post is part of my learning process and a great way to track
  my progress

# social links
twitter_username: duewestatx
github_username:  ad270

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima